plugins/general/bot/main.py
plugins/rss/bot/main.py
plugins/rss/langs/en.yml
plugins/rss/langs/fr.yml

Added wrong API token error message

Fixed error with twitter API token

---

plugins/voice/bot/asterix_names.txt

🔤 Ordralphabétix

---

requirements.txt

Use discord.py 2.0 release from PyPi instead of building from source

🧱 deps: use discord.py 2.0

---

.github/workflows/python-linter-pr.yaml
.github/workflows/python-linter-push.yaml
.github/workflows/python-linter.yaml

Cette PR est soumise à discussion quant-aux réglages.
Dans l'état actuel, le linter vérifie non seulement que le code Python est correct (pas de fonction appelée non définie par exemple), indique les morceaux de code inutiles (une fonction importée mais non utilisée) mais ausi vas reformater selon la PEP-8 pour que le code soit lisible par les personnes habituées à travailler en PEP-8.
Je pense que ça permettrai d'avoir un code bien plus uniforme, là où je sais que chacun à ses petites habitudes. Cependant il y avait déjà eu le débat sur Discord à propos de certains formatages, pas forcément autorisés par la PEP-8 qui semble pour certains plus clairs que d'autres.
Que faisons-nous ?

🧫 Ajout d'un linter Python

---

plugins/misc/langs/en.yml

Cette PR résout un problème lié à une malformation de fichier YAML avec les traductions du plugin `misc`qui empêchait l'anglais de charger dans certains cas.
S'il n'y a pas d'objection je mergerais ça rapidos, c'est un petit fix de rien du tout.

💬fix(misc): translation issues

---

plugins/roleLink/langs/en.yml
plugins/roleLink/langs/fr.yml

Cette PR résout un problème de consistance dans les message d'aide du plugin roleLink.
Closes #16

Fix rolelink command name inconsistency

---

bot/utils/languages.py
bot/utils/sconfig.py

La configuration de language était cassée car par défaut l'information est retournée sous forme de chaîne (`en` par exemple), alors qu'elle est stockée sous forme d'entier par la commande config.
Pour régler ce problème, la fonction `!config language` a été modifiée pour stocker la langue en utilisant une chaîne de caractère.

🗣Fix for translation configuration

---

bot/utils/perms.py
utils.py

La commande de permissions ne fonctionnait plus à cause d'une modification de `discord.py` concernant la récupération de l'avatar.
Closes #92.

⚙ Fix for perms command

---

bot/utils/sconfig.py
plugins/help/help.py
utils.py

Depuis une mise à jour de `discord.py`, les fonctions `bot.remove_cog` et `teardown` sont devenues asynchrones.
C'est pour cette raison que la console recevais un certain nombre d'erreurs liées au déchargement des plugins.
L'utilisation de fonctions asynchrones quand nécessaire a réglé ce problème.

🧹 Remove console spam when stopping the bot

---

plugins/wormhole/credits.md
plugins/wormhole/wormhole.py

Avant cette PR, quand le webhook d'un wormhole est supprimé, le programme ne s'adapte pas et n'en créé pas de nouveau.
Cette PR résout ce problème et ajoute un message d'erreur dans la console dans le cas où le message n'a pas pu être édité.
Closes #96.

🕳 Fix webhook issues when deleted

---

plugins/help/help.py

Cette PR retire les accents graves affichés à la fin du message d'aide pour les commandes ayant beaucoup de sous-commanbes comme par exemple la commande de configuration.

❓Fix long subcommand list in help

---

start.py

Avec cette PR, le bot se lance en mode ne pas déranger et retourne sur le statut en ligne une fois toutes les extensions chargées.
De cette manière, il y a un indicateur visuel du côté de Discord qui indique quand est-ce que le bot peut être utilisé.

⏳  Show when the bot is loading

---

plugins/general/general.py

Cette PR règle le problème concernant la commande `!hs` pour les salons threads et les salons forums.
J'ai aussi fait un tout petit peu de nettoyage en supprimant des imports non nécessaires.
Closes #124.

😡 Fix hs command for threads

---

plugins/voice/config.yaml
plugins/voice/voice.py

Petite correction de bug sur le système de noms de salons.
Tout est corrigé, si aucune clé pour l'API de randommer n'est spécifié dans la config, les noms d'Astérix sont utilisés en fallback (au lieu du vieux "None" d'avant)

🐛 fix(voice): fix voice channel random name

---

plugins/wormhole/wormhole.py

Cette PR résout différent problèmes avec le plugin wormhole.
Tout d'abord, cette PR résout #154 (et #149), et permet à nouveau aux réponses de fonctionner.
Ensuite, cette PR résout #136 et ajoute l'embed de réponse à la liste des embeds au moment d'éditer un message.
Cette PR résout aussi un problème lié à la vérification faite sur le message avant la modification, qui empêchait un bot de propager la modification d'un message à travers le wormhole (comme par exemple avec la commande `!stats`).
Enfin, cette PR résout #153 et répare `!wormhole unlink`.

🐛Various fixes for wormhole

---

plugins/xp/xp.py

Cette PR résout un problème empêchant d'utiliser un emoji par défaut de discord pour la réaction de levelup.

🐛 Fix normal emoji for levelup

---

core/config.py

During the guided configuration setup process, the administrator user IDs are currently stored as strings, which make them unusable in the bot code (as they are then compared and treated as integers).
This PR fixes the configuration setup script. Affected configuration files will have to be manually fixed.

:bug: fix: use int for admin users in config setup

---

.github/FUNDING.yml

The current funding link redirects to the Gunivers' patreon page, which is not used anymore. This PR updates the funding link to redirect people to our Altearn donation page, which currently uses HelloAsso.

:memo: feat: update funding url to our custom page

---

plugins/admin/admin.py

This PR should fix two bugs related to admin commands:
- the `reload`/`add_cog`/`del_cog` didn't await the lib coroutines and were thus not reloading anything (+ they used the old plugin structure format)
- the `shutdown` command, when trying to remove `__pycache__` files, was also deleting cache in the environment folder, thus failing for a few libs that actually used these folders

Fix admin commands

---

plugins/logs/logs.py

Cette PR résout une erreur affichée avec les logs d'activés :
```
Traceback (most recent call last):
File "/home/ascpial/Projets/Gipsy/venv/lib64/python3.11/site-packages/discord/client.py", line 441, in _run_event
await coro(*args, **kwargs)
File "/home/ascpial/Projets/Gipsy/plugins/logs/logs.py", line 552, in on_member_update
if 'members' not in self.get_flags(before.guild.id):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/ascpial/Projets/Gipsy/plugins/logs/logs.py", line 109, in get_flags
flags = self.bot.get_cog('ConfigCog').LogsFlags().int_to_flags()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ConfigCog.LogsFlags.int_to_flags() missing 1 required positional argument: 'i'
```

🐛 Fix error with logs enable

---

bot/utils/errors.py
core/__init__.py
core/config.py
core/logger.py
plugins/admin/admin.py
plugins/antikikoo/antikikoo.py
plugins/giveaways/giveaways.py
plugins/hypesquad/hypesquad.py
plugins/inviteTracker/inviteTracker.py
plugins/messageManager/messageManager.py
plugins/permissions/permissions.py
plugins/roleLink/roleLink.py
plugins/rss/rss.py
plugins/thanks/thanks.py
plugins/voice/voice.py
plugins/welcome/welcome.py
plugins/xp/xp.py
start.py
utils.py

Cette PR modifie le système de logs actuels avec une uniformisation des sorties et des méthodes d'écriture de logs sur tout le bot.
Chaque plugin dispose de son propre logger à son nom.
Cette PR résout aussi des ordres d'imports et quelques imports inutils.

🔊 More consistent logs across the bot

---

plugins/misc/misc.py

La commande `!cookie` et la commande `!hoster` ne fonctionnaient pas dans les threads et les forums.
Fix #188.

🐛 Fix cookie and hoster in threads

---

plugins/roleLink/langs/en.yml
plugins/roleLink/langs/fr.yml
plugins/roleLink/roleLink.py

Lors de la migration des plugins depuis le repo secondaire au repo principal, les fichiers de traduction du plugin roleLink ont étés perdus.
Ils sont de retour, avec en plus un fix pour un espace manquant :
Fixes #169.

🐛 Fix missing translations for rolelink

---

plugins/youtubeTrackingRemover/config/options.json
plugins/youtubeTrackingRemover/credits.md
plugins/youtubeTrackingRemover/langs/en.yml
plugins/youtubeTrackingRemover/langs/fr.yml
plugins/youtubeTrackingRemover/youtubeTrackingRemover.py

Ce plugin remplace les messages envoyés et contenant un lien YouTube avec des paramètres
Fonctionne sur activation de l'option de config serveur `enable_youtube_tracking_remover`
Le bouton "?" affiche un petit texte explicatif localisé :

✨ feat: add youtube tracking remover

---

plugins/monitoring/config.yaml
plugins/monitoring/credits.md
plugins/monitoring/monitoring.py
requirements.txt

Implement UptimeKuma push monitoring

:sparkles: feat: add heartbeat monitoring plugin

---

bot/utils/errors.py
langs/en.yml
langs/fr.yml
plugins/groups/groups.py
plugins/groups/langs/en.yml
plugins/groups/langs/fr.yml

Cette PR résout différents problèmes avec le module `groups` :
- certaines variables n'ont pas été renommées lors du refactor ;
- des commandes de configurations n'ont pas été correctement déplacée lors d'un autre refactor ;
- des erreurs liées au plugin `groups` ont étés déplacées depuis le cœur dans le plugin.
Fixes #232.
Fixes #255.
---
Checklist :

🐛 Updates to groups

---

plugins/rss/langs/en.yml
plugins/rss/rss.py

L'ajout ne fonctionnait pas à cause d'une typo et l'affichage ne fonctionnais pas à cause d'un changement de nom de variable mal effectué.

🐛 Fix adding and sending web rss feed

---

plugins/wormhole/wormhole.py

Le spoiler est correctement affiché quand un fichier est transmis par le wormhole.
Maintenant, la comparaison du contenu des messages est exacte puisque l'édition des messages est supporté.
De plus, le bot vérifiera les attachment pour supprimer le bon message. Pour ce faire, il vérifie le nom du fichier, sa taille, et si il est activé en tant que spoiler ou non.

🐛 Fix spoiler and message deletion
