- plugins/ban/bot/main.py
- plugins/ban/langs/en.yml
- plugins/ban/langs/fr.yml
Il fallait aussi ajouter le Discord d'Altearn, non ?
Et surtout, SURTOUT : Laizo a une folle envie de pouvoir s'auto-bannir (évidemment on lui dit pas que c'est maintenant possible, on le laisse découvrir)
> 🔫 feat(ban) : Ajout d'Altearn + Auto-ban

- .gitignore
- bot/utils/errors.py
- configs/.gitkeep
- configs/TO_REMOVE.md
- langs/en.yml
- langs/fr.yml
- plugins/misc/misc.py
- plugins/rss/rss.py
- plugins/wormhole/wormhole.py
- requirements.txt
- start.py
- utils.py
> **Note**
> 
> Cette PR est liée à https://github.com/Gunivers/Gipsy-plugins/pull/9
> Les deux doivent donc être review conjointement
Cette PR remet de l'ordre dans le répo en supprimant les plugins de base du répo de plugin tout en permettant, grâce au gitignore, d'avoir les deux répo en un seul.
Elle vient également corriger de nombreux petits bugs et améliore légèrement l'aspect visuelle de cetraines réponses de Gipsy
> 🩹-Some-plugin-fixes

- LICENSE.md
- LICENSE_en.md
- README.md
- bot/__init__.py
- bot/args.py
- bot/checks.py
- bot/utils/configManager.py
- bot/utils/errors.py
- bot/utils/gunivers.py
- bot/utils/languages.py
- bot/utils/perms.py
- bot/utils/sconfig.py
- bot/utils/timeclass.py
- core/config.py
- credits.md
- data/model.sql
- docs/faq.md
- langs/en.yml
- langs/fr.yml
- setup.py
- start.py
- utils.py
It add new license (CeCILL) and associated header and credit files.
> Application of CeCILL licence

- plugins/antikikoo/antikikoo.py
- plugins/antikikoo/langs/en.yml
- plugins/antikikoo/langs/fr.yml
Cette PR ajoute la possibilité de modifier les paramètres du plugin antikikoo avec la commande `!config`.
Ce n'est pas un travail très propre mais ce sera retravaillé avec la modification du système de configuration.
Closes #104.
> 🔓Add configuration commands

- plugins/inviteTracker/credits.md
- plugins/inviteTracker/inviteTracker.py
- plugins/inviteTracker/langs/en.yml
- plugins/inviteTracker/langs/fr.yml
Cette PR règle un problème de rate limit au moment où un utilisateur rejoint un serveur lié au fetch de chaque invitation utilisée par le serveur.
J'ai aussi modifié différentes choses pour améliorer glboalement le plugin.
Closes #98.
> 🕵 Fix rate limit and improve things

- plugins/xp/xp.py
Cette PR résout un bug concernant les catégories en noxp, ainsi que les threads (et par extension les forums).
Cette PR résout aussi un problème qui faisait que le cache n'était pas correctement chargé et que la commande d'édition de salons ne mettait pas à jour le cache.
Closes #99.
> ⬆ Noxp channels and config update fixes

- core/config.py
- plugins/rss/setup.py
- plugins/wormhole/wormhole.py
- requirements.txt
- setup.py
- start.py
Puisque python est un peu con, on met à jour la librairie LRFutils pour éviter les problèmes.
> ⬆Upgrade LRFutils to 0.1.2 

- .github/workflows/deploy_gipsy-beta.yaml
- .github/workflows/deploy_gipsy-prod.yaml
Cette PR résout le problèmes qui empêche le déploiment automatique du code sur gipsy beta et gipsy prod de fonctionner correctement.
> 💚 Fix deploy for gipsy beta and prod

- plugins/messageManager/langs/en.yml
- plugins/messageManager/langs/fr.yml
- plugins/messageManager/messageManager.py
> :bug: Fix #137

- .github/workflows/deploy_gipsy-beta.yaml
- .github/workflows/deploy_gipsy-prod.yaml
⚠️ IL EST NÉCESSAIRE D'AJOUTER LES SECRETS AVANT DE MERGE !
> :construction_worker: ci: automatically restart bot after deployment

- plugins/groups/groups.py
- plugins/wormhole/credits.md
Cette PR modifie la majuscule au nom de fantomitechno dans les crédits.
Cette PR supprimes aussi la mention dans le code, puisque c'est redondant et inconsistant.
> 📝 Fix credits for fantomitechno

- plugins/__template__/__template__.py
- plugins/__template__/credits.md
Cette PR résout un bug très mineur lié au fait que la traduction n'était pas "awaited".
Closes #164.
> 🐛 Template now works

- bot/utils/languages.py
Cette PR résout le problème de mise à jour du bot depuis la version `master` vers la version `beta` à cause d'un changement de format.
Closes #151.
> 🐛 Support for bot update for translations

- utils.py
> 🐛 Fix error in console when loading

- plugins/logs/logs.py
> Fix avatar URL formatting in Logs cog

- plugins/general/general.py
> Fix stats commands outside of git repo

- plugins/wormhole/wormhole.py
> Fix: `help wormhole link` shows weird default value

- core/logger.py
- start.py
> 🐛 Fix traceback are now shown

- core/config.py
- plugins/rss/setup.py
Fix #83 and some minor typos in the setup script
> Fix setup script

- plugins/admin/admin.py
Previous fix (#216) has been accidentally reverted by commit 281c6f2e
> Fix add_cog and del_cog admin commands

- plugins/xp/xp.py
Cette PR résout un bug créé lors du refactor, qui mélangeait deux variables différentes.
> 🐛 Fix xp configuration bug

- plugins/channelArchive/channelArchive.py
> 🐛 Fix missformed queries in channelArchive

- plugins/xp/xp.py
- fix the guild cache access leading to repeating KeyError
- fix some typing and lint issues in the main cog file
> Fix XP cache access
